# Generated by Django 6.0.3 on 2026-04-05 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipAndRecommendation',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tip_type', models.CharField(choices=[('tip', 'Tip'), ('quote', 'Quote'), ('recommendation', 'Recommendation'), ('guidance', 'Guidance')], max_length=30)),
                ('severity_target', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tips_and_recommendations',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('preliminary', 'Preliminary'), ('final', 'Final')], max_length=20)),
                ('depression_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anxiety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stress_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_severity', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=30, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('mood_trend', models.JSONField(blank=True, null=True)),
                ('questionnaire_summary', models.JSONField(blank=True, null=True)),
                ('journal_summary', models.JSONField(blank=True, null=True)),
                ('dominant_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('data_days_count', models.IntegerField(blank=True, null=True)),
                ('created_from_days', models.IntegerField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'indexes': [models.Index(fields=['user', 'assessment_type'], name='assessments_user_id_00550c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDailyTip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shown_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_to', to='assessment.tipandrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_tips',
                'unique_together': {('user', 'shown_date')},
            },
        ),
    ]
