# Generated by Django 6.0.3 on 2026-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_admin_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_whatsapp_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
