# Generated by Django 6.0.3 on 2026-04-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('system_suggested', 'System Suggested'), ('user_selected', 'User Selected')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to='assessment.assessment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='accounts.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_patient_requests',
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientRelationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='accounts.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relationships', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship', to='clinic.doctorpatientrequest')),
            ],
            options={
                'db_table': 'doctor_patient_relationships',
            },
        ),
        migrations.CreateModel(
            name='DoctorRegistrationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_logs', to='accounts.admin')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_logs', to='accounts.doctor')),
            ],
            options={
                'db_table': 'doctor_registration_log',
            },
        ),
        migrations.CreateModel(
            name='DoctorConditionTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('trauma', 'Trauma'), ('ocd', 'OCD'), ('general', 'General')], max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_tags', to='accounts.doctor')),
            ],
            options={
                'db_table': 'doctor_condition_tags',
                'indexes': [models.Index(fields=['condition'], name='doctor_cond_conditi_aef76a_idx'), models.Index(fields=['doctor'], name='doctor_cond_doctor__16b95e_idx')],
                'unique_together': {('doctor', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientMessageUser',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='clinic.doctorpatientrelationship')),
            ],
            options={
                'db_table': 'doctor_patient_messages_user',
                'indexes': [models.Index(fields=['relationship', 'sent_at'], name='doctor_pati_relatio_9bf896_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientMessageDoctor',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.doctor')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_messages', to='clinic.doctorpatientrelationship')),
            ],
            options={
                'db_table': 'doctor_patient_messages_doctor',
                'indexes': [models.Index(fields=['relationship', 'sent_at'], name='doctor_pati_relatio_280d92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='doctorpatientrequest',
            index=models.Index(fields=['doctor', 'status'], name='doctor_pati_doctor__b4f455_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorpatientrequest',
            index=models.Index(fields=['user', 'status'], name='doctor_pati_user_id_9a997a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientrelationship',
            unique_together={('doctor', 'user')},
        ),
        migrations.AddIndex(
            model_name='doctorregistrationlog',
            index=models.Index(fields=['doctor'], name='doctor_regi_doctor__d06574_idx'),
        ),
    ]
