# Generated by Django 6.0.3 on 2026-04-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_patient_messages',
            },
        ),
        migrations.RemoveIndex(
            model_name='doctorpatientmessagedoctor',
            name='doctor_pati_relatio_280d92_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctorpatientmessageuser',
            name='doctor_pati_relatio_9bf896_idx',
        ),
        migrations.AddField(
            model_name='doctorpatientmessage',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clinic.doctorpatientrelationship'),
        ),
        migrations.RemoveField(
            model_name='doctorpatientmessagedoctor',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='doctorpatientmessagedoctor',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='doctorpatientmessageuser',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='doctorpatientmessageuser',
            name='sender',
        ),
        migrations.AddIndex(
            model_name='doctorpatientmessage',
            index=models.Index(fields=['relationship', 'sent_at'], name='doctor_pati_relatio_b13b69_idx'),
        ),
        migrations.DeleteModel(
            name='DoctorPatientMessageDoctor',
        ),
        migrations.DeleteModel(
            name='DoctorPatientMessageUser',
        ),
    ]
