# Generated by Django 6.0.3 on 2026-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctorrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconditiontag',
            name='condition',
            field=models.CharField(choices=[('child_adolescent', 'طب نفس الأطفال والمراهقين'), ('geriatric', 'الطب النفسي للمسنين (الشيخوخة)'), ('addiction', 'طب الإدمان'), ('forensic', 'الطب النفسي الشرعي'), ('psychosomatic', 'الطب النفسي الجسدي'), ('neuropsychiatry', 'الفسيولوجيا العصبية السريرية والطب النفسي العصبي'), ('psychotic', 'الفصام والاضطرابات الذهانية'), ('mood', 'اضطرابات المزاج (الاكتئاب الحاد، والاضطراب ثنائي القطب)'), ('anxiety_phobia_ptsd', 'اضطرابات القلق، الرهاب، واضطراب ما بعد الصدمة (PTSD)')], max_length=50),
        ),
    ]
