# Generated by Django 6.0.3 on 2026-04-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scale', 'Scale'), ('text', 'Text'), ('yes_no', 'Yes / No')], max_length=30)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('display_order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'initial_survey_questions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InitialSurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.initialsurveyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'initial_survey_responses',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
