# Generated by Django 6.0.3 on 2026-04-05 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_order', models.IntegerField()),
                ('options', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'questionnaire_questions',
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('questionnaire_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField()),
                ('scoring_ranges', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'questionnaire_types',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entries',
            },
        ),
        migrations.CreateModel(
            name='JournalAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('detected_symptoms', models.JSONField(blank=True, null=True)),
                ('disorder_scores', models.JSONField(blank=True, null=True)),
                ('dominant_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_indicators', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='tracking.journalentry')),
            ],
            options={
                'db_table': 'journal_analysis',
            },
        ),
        migrations.CreateModel(
            name='JournalSharingPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_full_journal', models.BooleanField(default=False)),
                ('share_analysis_only', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_permissions', to='accounts.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_sharing_permissions',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=30, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_sessions', to=settings.AUTH_USER_MODEL)),
                ('questionnaire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracking.questionnairetype')),
            ],
            options={
                'db_table': 'questionnaire_sessions',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.IntegerField()),
                ('score', models.IntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tracking.questionnairequestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tracking.questionnairesession')),
            ],
            options={
                'db_table': 'questionnaire_answers',
            },
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='questionnaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tracking.questionnairetype'),
        ),
        migrations.CreateModel(
            name='DailyMoodEntry',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_level', models.IntegerField()),
                ('mood_label', models.CharField(blank=True, choices=[('very_bad', 'Very Bad'), ('bad', 'Bad'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=50, null=True)),
                ('reason_note', models.TextField(blank=True, null=True)),
                ('recorded_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_mood_entries',
                'indexes': [models.Index(fields=['user', 'recorded_date'], name='daily_mood__user_id_3d16b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_date', models.DateField(default=django.utils.timezone.localdate)),
                ('mood_completed', models.BooleanField(default=False)),
                ('phq9_completed', models.BooleanField(default=False)),
                ('gad7_completed', models.BooleanField(default=False)),
                ('pss10_completed', models.BooleanField(default=False)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('journal_completed', models.BooleanField(default=False)),
                ('all_completed', models.BooleanField(default=False)),
                ('tip_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_progress',
                'indexes': [models.Index(fields=['user', 'progress_date'], name='daily_progr_user_id_a9248a_idx')],
                'unique_together': {('user', 'progress_date')},
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'entry_date'], name='journal_ent_user_id_a328f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalsharingpermission',
            unique_together={('user', 'doctor')},
        ),
        migrations.AddIndex(
            model_name='questionnairesession',
            index=models.Index(fields=['user', 'session_date'], name='questionnai_user_id_c2b250_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairesession',
            unique_together={('user', 'questionnaire_type', 'session_date')},
        ),
    ]
