# Generated by Django 6.0.3 on 2026-04-05 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymoodentry',
            unique_together={('user', 'recorded_date')},
        ),
    ]
