# Generated by Django 6.0.3 on 2026-04-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('related_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.admin')),
            ],
            options={
                'db_table': 'admin_notifications',
                'indexes': [models.Index(fields=['admin', 'is_read'], name='admin_notif_admin_i_e8ff5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('related_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.doctor')),
            ],
            options={
                'db_table': 'doctor_notifications',
                'indexes': [models.Index(fields=['doctor', 'is_read'], name='doctor_noti_doctor__14d518_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('related_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notifications',
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_ea6762_idx')],
            },
        ),
    ]
