# Generated by Django 6.0.3 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='related_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctornotification',
            name='related_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='related_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
