# Generated by Django 6.0.3 on 2026-05-30 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctor_email_notifications_doctor_push_notifications_and_more'),
        ('notifications', '0002_alter_adminnotification_related_entity_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_uuid', models.UUIDField(db_index=True)),
                ('notification_role', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=20)),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('push', 'Web Push')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_delivery_logs',
            },
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='notification_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='notification_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat Message'), ('appointment', 'Appointment/Meeting'), ('assessment', 'Assessment/Daily Task'), ('system', 'System Alert/Tip'), ('general', 'General Notification')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='related_entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctornotification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat Message'), ('appointment', 'Appointment/Meeting'), ('assessment', 'Assessment/Daily Task'), ('system', 'System Alert/Tip'), ('general', 'General Notification')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctornotification',
            name='related_entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat Message'), ('appointment', 'Appointment/Meeting'), ('assessment', 'Assessment/Daily Task'), ('system', 'System Alert/Tip'), ('general', 'General Notification')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='related_entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'constraints': [models.UniqueConstraint(fields=('endpoint',), name='unique_push_endpoint')],
            },
        ),
    ]
